[pytest]
markers =
    login: marks tests as login (deselect with '-m "not login"')
    sanity: marks tests as sanity (deselect with '-m "not sanity"')
    recommend: marks tests as recommend (deselect with '-m "not recommend"')
    serial